**** Job starts ****
Sun Jan  7 05:12:44 PM EST 2024
**** JHPCE info ****
User: lhuuki
Job id: 1489049
Job name: ../08_deconvolution_DISSECT_test
Node name: compute-148
Task id: 
Unloading LIBD SLURM module for dissect/dc45940c
Loading LIBD SLURM module for dissect/dc45940c

Currently Loaded Modules:
  1) JHPCE_ROCKY9_DEFAULT_ENV   3) ruby/3.2.2     5) conda/3-23.3.1
  2) JHPCE_tools/3.0            4) rmate/1.5.10   6) dissect/dc45940c

 

Traceback (most recent call last):
  File "prepare_data.py", line 246, in <module>
    dataset(config)
  File "prepare_data.py", line 49, in dataset
    X_real = pd.read_table(config["test_dataset"], index_col=0)
  File "/jhpce/shared/libd/core/dissect/dc45940c/dissect_env/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/jhpce/shared/libd/core/dissect/dc45940c/dissect_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 779, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/jhpce/shared/libd/core/dissect/dc45940c/dissect_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/jhpce/shared/libd/core/dissect/dc45940c/dissect_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/jhpce/shared/libd/core/dissect/dc45940c/dissect_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/jhpce/shared/libd/core/dissect/dc45940c/dissect_env/lib/python3.8/site-packages/pandas/io/common.py", line 786, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../bulk.txt'
