**** Job starts ****
Tue Feb  6 03:00:49 PM EST 2024
**** JHPCE info ****
User: neagles
Job id: 1933604
Job name: 02_sra_biosample
Node name: compute-111
Task id: 
Loading conda_R/4.3
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
here() starts at /dcs04/lieber/lcolladotor/deconvolution_LIBD4030/Human_DLPFC_Deconvolution
Error in `mutate()`:
ℹ In argument: `isolate = str_replace(a$sample_name,
  "^(.*?)_(.*?)_(.*?)_(.*)$", "\\4 sample from \\3 position of donor \\2 from
  dataset \\1")`.
Caused by error:
! object 'a' not found
Backtrace:
     ▆
  1. ├─readr::write_tsv(...)
  2. │ └─readr::write_delim(...)
  3. │   ├─base::stopifnot(is.data.frame(x))
  4. │   └─base::is.data.frame(x)
  5. ├─dplyr::select(...)
  6. ├─dplyr::mutate(...)
  7. ├─dplyr:::mutate.data.frame(...)
  8. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  9. │   ├─base::withCallingHandlers(...)
 10. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 11. │     └─mask$eval_all_mutate(quo)
 12. │       └─dplyr (local) eval()
 13. ├─stringr::str_replace(...)
 14. │ └─stringr:::check_lengths(string, pattern, replacement)
 15. │   └─vctrs::vec_size_common(...)
 16. └─base::.handleSimpleError(`<fn>`, "object 'a' not found", base::quote(NULL))
 17.   └─dplyr (local) h(simpleError(msg, call))
 18.     └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
Execution halted
